repos:
  - repo: local
    hooks:
      - id: flake8-critical
        name: flake8 critical errors
        entry: poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: poetry run mypy cmr tests
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        stages: [pre-push]
